### ISSUE TITLE
 trying to pull the player season stats via nodejs

### ISSUE THREAD

**Issue by olliefu** [stattleship/stattleship-api#18]
Hey All - I am trying to pull the player season stats. Is this right?

stattleship.player_season_stats('baseball', 'mlb', params).then(function(player_season_stats) {
player_season_stats.forEach(function(element, index, array) {
//console.log(element.name);
console.log(element.batting_average);
});
});

**Comment by dthyresson** [comment]
Doing some issue review and catch up.

@olliefu did you get this work work?

Since you were doing player baseball stats in January, it's likely that the season at that time was set to `mlb-2017` and there hadn't been any games yet.

You would have had to set a prior season id and we just backfilled the season stats for last season in March.

Give it a go again and if no luck, let me know here or we have a Slack support community at https://fanboat.stattleship.com/
